language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements-dev.txt --use-mirrors
# command to run tests
script:
  - coverage run --source=box setup.py test
after_success:
  - coveralls
